### ISSUE TITLE
Support for mk20dx256 and similar

### ISSUE THREAD

**Issue by WyseNynja** [abcminiuser/lufa#100]
I have a few models of Teensy and noticed that lufa doesn't seem to support all of them.

    mk66fx1m0    Teensy 3.6
    mk64fx512    Teensy 3.5
    mk20dx256    Teensy 3.2 & 3.1
    mk20dx128    Teensy 3.0
    mkl26z64     Teensy LC
    at90usb1286  Teensy++ 2.0
    atmega32u4   Teensy 2.0
    at90usb646   Teensy++ 1.0
    at90usb162   Teensy 1.0

Luckily I have a Teensy++ 2.0 and so am able to use lufa, but I wanted to know if support was planned or even possible for the mk* models. I am pretty new to USB programming and am not sure how much work this would be or if I should be using a similar library for those instead.

**Comment by abcminiuser** [comment]
LUFA only supports the 8-bit USB AVRs (now a dying breed, they're quite old!) along with partial UC3 support (also ancient, and shouldn't be used since their compiler is EOL) and partial XMEGA support (works, but has poor performance).

When I wrote the LUFA stack I made some design decisions necessary to make the stack work within the extremely limited RAM budget of the smallest devices, and the rather odd USB controller design used in the USB AVR-8 devices. Unfortunately, while that results in a codebase and API that works fine on the devices it was designed for, it's a poor candidate for porting to more modern and capable devices.

I highly recommend using the Atmel ASF stack on their newer processors, and the other vendor stacks on other manufacturer's parts. They will (hopefully) be somewhat more portable and ultimately more performant as they will most likely be DMA and interrupt driven at their core.

I hope to sunset LUFA when/if the original parts go out of production, as then it will have served its purpose in giving a working USB stack to the original USB AVR8 devices which lacked any real first party support. One day I might look into writing another USB stack that's portable and open source, but having done something like this twice now for companies I've worked for, I'm a bit over writing new USB libraries at this point unless there's a real community need for it.
