### ISSUE TITLE
LUFA extension Atmel Studio 7 - update for version 210130

### ISSUE THREAD

**Issue by Principia4834** [abcminiuser/lufa#169]
Dean
It looks like the LUFA extension for Atmel / Microchip Studio 7 is not using LUFA 210130. Would it be possible to add this update to your TODO list?
Andy

**Comment by abcminiuser** [comment]
I actually stripped out all the Atmel Studio support from the repository; it was hard to maintain, and since the rebranding to Microchip Studio I lost access to the extension on the Atmel/Microchip Gallery, so I couldn't update it even if I wanted to.

The current direction seem to be towards MPLAB-X, and the Atmel Software Framework that I used for the LUFA integration was effectively deprecated for ATMEL Start.

**Comment by Principia4834** [comment]
Ok - thanks for the update. I've grabbed the 2017 extension files and I'll probably build for myself.
